# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DLStempindex <- function(myDD, myovi, myP, Zout, Zoutovi) {
    .Call(`_tempsuitcalc_DLStempindex`, myDD, myovi, myP, Zout, Zoutovi)
}

DLStempindexnew <- function(myDD, myP, Zout, Aoutmov) {
    .Call(`_tempsuitcalc_DLStempindexnew`, myDD, myP, Zout, Aoutmov)
}

rcpp_hello_world <- function() {
    .Call(`_tempsuitcalc_rcpp_hello_world`)
}

WaterVolumeSim <- function(temp, dewp, rain, alt, lat, Vout) {
    .Call(`_tempsuitcalc_WaterVolumeSim`, temp, dewp, rain, alt, lat, Vout)
}

